#apiVersion: v1
#kind: Service
#metadata:
#  name: aspnetapp
#spec:
#  selector:
#    app: aspnetapp
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#  externalTrafficPolicy: Cluster
#  type: LoadBalancer
#---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aspnetapp
spec:
  selector:
    matchLabels:
      app: aspnetapp
  serviceName: "aspnetapp"
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      terminationGracePeriodSeconds: 10
      containers:
        - name: aspnetapp
          image: eggboy/aspnetapp:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: aspnetapp
