apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Cluster
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: sample
        image: eggboy/aspnetapp:0.0.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 800M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: sample
